theme="amp"
baseURL = "https://inductor.me/"
languageCode = "ja-JP"
title = "inductor.me"
copyright = "Â© 2018 inductor."
canonifyurls = true

[params]
  description = "shitty note" #optional

# optional
[social]
  twitter = "_inductor_"
  github = "kelaductor"
  facebook = "kelaphone"
  gplus = ""
  linkedin = "kelaductor"
